### ISSUE TITLE
Clustercontrol support for Gov-cloud

### ISSUE THREAD

**Issue by skhadka-securus** [severalnines/docker#26]
I am trying to set cluster control on Us-gov-east but the region is not supported. Could you please look into adding AWS-GOV regions .

**Comment by ashraf-s9s** [comment]
Hi @skhadka-securus 

This has nothing to do with the Docker image. I don't think that we can support the AWS-GOV since the region is not listed publicly and requires signup, as shown here: https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/getting-started-sign-up.html .

Nothing much that I can do to help you in this matter, thus, I'm going to close this issue.
